name: Build libraries + example client
on:
    push:
        branches-ignore:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build:
        runs-on:
            labels: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: liberica
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4
            - name: Build
              run: |
                  ./gradlew build --info --stacktrace

